---
# Simple workflow for deploying static content to GitHub Pages
name: tests

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [main]
  pull_request:
    branches: [main, $protected-branches]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "^1.21.4"
      - name: execute tests
        working-directory: wasm/toSql
        run: go test
      - name: confirm it builds
        run: make build-wasm
